# Generated by Django 5.1.3 on 2024-11-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_generalannouncement_generalannouncementimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalannouncement",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="announcements/"),
        ),
        migrations.DeleteModel(
            name="GeneralAnnouncementImage",
        ),
    ]
