# Generated by Django 5.1.3 on 2024-11-12 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_generalannouncement_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellitemimage",
            name="item",
        ),
        migrations.DeleteModel(
            name="DonationImage",
        ),
        migrations.DeleteModel(
            name="SellItemImage",
        ),
    ]
