# Generated by Django 5.1.3 on 2024-11-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_remove_sellitemimage_item_delete_donationimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
