# Generated by Django 5.1.3 on 2024-11-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_sellitem_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalannouncement",
            name="phone",
            field=models.CharField(default="0000000000", max_length=15),
        ),
    ]
