# Generated by Django 5.1.3 on 2024-11-20 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("posts", "0010_alter_comment_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content_type",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
