# Generated by Django 5.1.3 on 2024-11-20 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_alter_comment_content_type_alter_comment_object_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="object_id",
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="posts.generalannouncement",
            ),
            preserve_default=False,
        ),
    ]
