# Generated by Django 5.1.3 on 2024-11-20 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0012_remove_comment_content_type_remove_comment_object_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
