# Generated by Django 5.1.3 on 2024-12-11 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0015_remove_comment_post_remove_generalannouncement_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="post",
        ),
    ]
