# Generated by Django 5.1.3 on 2024-12-11 12:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("posts", "0016_remove_comment_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="Comments",
        ),
    ]
