# Generated by Django 5.1.3 on 2024-12-13 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0018_rename_comments_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="object_id",
        ),
        migrations.AddField(
            model_name="comment",
            name="general_announcement",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="posts.generalannouncement",
            ),
            preserve_default=False,
        ),
    ]
