# Generated by Django 5.1.3 on 2024-12-13 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("posts", "0019_remove_comment_content_type_remove_comment_object_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="general_announcement",
        ),
        migrations.AddField(
            model_name="comment",
            name="content_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="object_id",
            field=models.PositiveIntegerField(default="default string"),
            preserve_default=False,
        ),
    ]
