# Generated by Django 5.1.4 on 2025-01-21 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("barcode_scanner", "0017_alter_wasteimage_waste_item"),
        ("posts", "0021_donationcomment_generalannouncementcomment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellitem",
            name="user_role",
        ),
        migrations.AddField(
            model_name="sellitem",
            name="post_type",
            field=models.CharField(
                choices=[("sell", "ประกาศขาย"), ("buy", "ประกาศซื้อ")],
                default="sell",
                max_length=10,
                verbose_name="ประเภทประกาศ",
            ),
        ),
        migrations.AddField(
            model_name="sellitem",
            name="related_waste",
            field=models.ManyToManyField(
                blank=True,
                related_name="sell_items",
                to="barcode_scanner.wasteimage",
                verbose_name="ขยะที่เกี่ยวข้อง",
            ),
        ),
        migrations.AlterField(
            model_name="sellitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="วันที่ประกาศ"),
        ),
        migrations.AlterField(
            model_name="sellitem",
            name="description",
            field=models.TextField(verbose_name="รายละเอียดสินค้า"),
        ),
        migrations.AlterField(
            model_name="sellitem",
            name="image",
            field=models.ImageField(
                upload_to="sell_items/", verbose_name="รูปภาพสินค้า"
            ),
        ),
        migrations.AlterField(
            model_name="sellitem",
            name="is_closed",
            field=models.BooleanField(
                default=False, verbose_name="ปิดการขายแล้วหรือยัง"
            ),
        ),
        migrations.AlterField(
            model_name="sellitem",
            name="location",
            field=models.CharField(max_length=255, verbose_name="พื้นที่สินค้า"),
        ),
        migrations.AlterField(
            model_name="sellitem",
            name="phone",
            field=models.CharField(max_length=15, verbose_name="เบอร์โทรติดต่อ"),
        ),
        migrations.AlterField(
            model_name="sellitem",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="ราคา (เฉพาะประกาศขาย)",
            ),
        ),
        migrations.AlterField(
            model_name="sellitem",
            name="title",
            field=models.CharField(max_length=255, verbose_name="หัวข้อประกาศ"),
        ),
        migrations.AlterField(
            model_name="sellitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไขประกาศ"),
        ),
        migrations.AlterField(
            model_name="sellitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้ประกาศ",
            ),
        ),
    ]
