# Generated by Django 5.1.4 on 2025-01-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0022_remove_sellitem_user_role_sellitem_post_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellitem",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
