# Generated by Django 5.1.4 on 2025-02-02 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0023_alter_sellitem_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellitem",
            name="image",
        ),
    ]
