# Generated by Django 5.1.4 on 2025-02-02 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0024_remove_sellitem_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="sell_items/")),
                (
                    "sell_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="posts.sellitem",
                    ),
                ),
            ],
        ),
    ]
