# Generated by Django 5.1.4 on 2025-02-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0025_sellitemimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellitem",
            name="image",
            field=models.ImageField(
                default=None, upload_to="sell_items/", verbose_name="รูปภาพสินค้า"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="SellItemImage",
        ),
    ]
