# Generated by Django 5.1.3 on 2024-12-11 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WasteItem",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="รหัสบาร์โค้ด"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="ชื่อผลิตภัณฑ์"),
                ),
                (
                    "waste_type",
                    models.CharField(max_length=100, verbose_name="ประเภทขยะ"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="waste_images/", verbose_name="รูปภาพผลิตภัณฑ์"
                    ),
                ),
                ("disposal_method", models.TextField(verbose_name="วิธีแยกขยะ")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="วันที่เพิ่มข้อมูล"
                    ),
                ),
            ],
        ),
    ]
