# Generated by Django 5.1.3 on 2024-11-20 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_alter_comment_object_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
