# Generated by Django 5.1.4 on 2024-12-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WasteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=100, unique=True)),
                ("product_name", models.CharField(max_length=255)),
                ("waste_type", models.CharField(max_length=50)),
                ("subtype", models.CharField(blank=True, max_length=50, null=True)),
                ("category", models.CharField(max_length=50)),
                (
                    "waste_image",
                    models.ImageField(blank=True, null=True, upload_to="waste_images/"),
                ),
                ("separation_method", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
