# Generated by Django 5.1.4 on 2025-01-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("barcode_scanner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="waste_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="wasteitem",
            name="waste_image",
        ),
        migrations.AddField(
            model_name="wasteitem",
            name="images",
            field=models.ManyToManyField(blank=True, to="barcode_scanner.wasteimage"),
        ),
    ]
