# Generated by Django 5.1.4 on 2025-01-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("barcode_scanner", "0002_wasteimage_remove_wasteitem_waste_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wasteitem",
            name="brand_name",
            field=models.CharField(
                default="Unknown", max_length=255, verbose_name="ชื่อยี่ห้อ"
            ),
        ),
        migrations.AddField(
            model_name="wasteitem",
            name="product_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product_images/",
                verbose_name="ภาพผลิตภัณฑ์",
            ),
        ),
        migrations.AlterField(
            model_name="wasteitem",
            name="barcode",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="เลขบาร์โค้ด"
            ),
        ),
        migrations.AlterField(
            model_name="wasteitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("recyclable", "สามารถรีไซเคิลได้"),
                    ("non_recyclable", "ไม่สามารถรีไซเคิลได้"),
                    ("hazardous", "ของเสียอันตราย"),
                    ("compostable", "สามารถย่อยสลายได้"),
                ],
                max_length=50,
                verbose_name="หมวดหมู่ของขยะ",
            ),
        ),
        migrations.AlterField(
            model_name="wasteitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
        ),
        migrations.AlterField(
            model_name="wasteitem",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                to="barcode_scanner.wasteimage",
                verbose_name="รูปภาพที่เกี่ยวข้อง",
            ),
        ),
        migrations.AlterField(
            model_name="wasteitem",
            name="product_name",
            field=models.CharField(
                max_length=255, verbose_name="ชื่อสินค้า / รุ่น / ประเภท"
            ),
        ),
        migrations.AlterField(
            model_name="wasteitem",
            name="separation_method",
            field=models.TextField(blank=True, null=True, verbose_name="วิธีการแยกขยะ"),
        ),
        migrations.AlterField(
            model_name="wasteitem",
            name="subtype",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="หมวดหมู่ย่อยของขยะ"
            ),
        ),
        migrations.AlterField(
            model_name="wasteitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไขล่าสุด"),
        ),
        migrations.AlterField(
            model_name="wasteitem",
            name="waste_type",
            field=models.CharField(
                choices=[
                    ("paper", "กระดาษ"),
                    ("plastic", "พลาสติก"),
                    ("metal", "โลหะ"),
                    ("glass", "แก้ว"),
                    ("e_waste", "e-waste"),
                    ("steel", "เหล็ก"),
                    ("others", "อื่นๆ"),
                ],
                max_length=50,
                verbose_name="ประเภทขยะหลัก",
            ),
        ),
    ]
