# Generated by Django 5.1.4 on 2025-01-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "barcode_scanner",
            "0003_wasteitem_brand_name_wasteitem_product_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="wasteitem",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("recyclable", "สามารถรีไซเคิลได้"),
                    ("non_recyclable", "ไม่สามารถรีไซเคิลได้"),
                    ("hazardous", "ของเสียอันตราย"),
                    ("compostable", "สามารถย่อยสลายได้"),
                ],
                max_length=50,
                null=True,
                verbose_name="หมวดหมู่ของขยะ",
            ),
        ),
        migrations.AlterField(
            model_name="wasteitem",
            name="waste_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paper", "กระดาษ"),
                    ("plastic", "พลาสติก"),
                    ("metal", "โลหะ"),
                    ("glass", "แก้ว"),
                    ("e_waste", "e-waste"),
                    ("steel", "เหล็ก"),
                    ("others", "อื่นๆ"),
                ],
                max_length=50,
                null=True,
                verbose_name="ประเภทขยะหลัก",
            ),
        ),
    ]
