# Generated by Django 5.1.4 on 2025-01-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("barcode_scanner", "0004_alter_wasteitem_category_alter_wasteitem_waste_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="wasteimage",
            name="subtype",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="หมวดหมู่ย่อย"
            ),
        ),
    ]
