# Generated by Django 5.1.4 on 2025-01-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("barcode_scanner", "0005_wasteimage_subtype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wasteitem",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="wasteitem",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="wasteitem",
            name="waste_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("plastic", "พลาสติก"),
                    ("paper", "กระดาษ"),
                    ("metal", "โลหะ"),
                    ("glass", "แก้ว"),
                    ("e_waste", "e-waste"),
                    ("steel", "เหล็ก"),
                    ("others", "อื่นๆ"),
                ],
                max_length=50,
                null=True,
                verbose_name="ประเภทขยะหลัก",
            ),
        ),
    ]
