# Generated by Django 5.1.4 on 2025-01-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("barcode_scanner", "0006_remove_wasteitem_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wasteimage",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="wasteimage",
            name="image",
        ),
        migrations.AddField(
            model_name="wasteimage",
            name="category",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="หมวดหมู่"
            ),
        ),
        migrations.AddField(
            model_name="wasteimage",
            name="separation_method",
            field=models.TextField(blank=True, null=True, verbose_name="วิธีการแยกขยะ"),
        ),
        migrations.AddField(
            model_name="wasteimage",
            name="waste_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ประเภทขยะ"
            ),
        ),
    ]
