# Generated by Django 5.1.4 on 2025-01-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "barcode_scanner",
            "0007_remove_wasteimage_created_at_remove_wasteimage_image_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wasteitem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="wasteitem",
            name="separation_method",
        ),
        migrations.RemoveField(
            model_name="wasteitem",
            name="subtype",
        ),
        migrations.RemoveField(
            model_name="wasteitem",
            name="waste_type",
        ),
        migrations.AddField(
            model_name="wasteimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="waste_images/",
                verbose_name="รูปภาพขยะ",
            ),
        ),
        migrations.AlterField(
            model_name="wasteimage",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("recyclable", "สามารถรีไซเคิลได้"),
                    ("non_recyclable", "ไม่สามารถรีไซเคิลได้"),
                    ("hazardous", "ของเสียอันตราย"),
                    ("compostable", "สามารถย่อยสลายได้"),
                ],
                max_length=50,
                null=True,
                verbose_name="หมวดหมู่",
            ),
        ),
        migrations.AlterField(
            model_name="wasteimage",
            name="waste_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("plastic", "พลาสติก"),
                    ("paper", "กระดาษ"),
                    ("metal", "โลหะ"),
                    ("glass", "แก้ว"),
                    ("e_waste", "e-waste"),
                    ("steel", "เหล็ก"),
                    ("others", "อื่นๆ"),
                ],
                max_length=50,
                null=True,
                verbose_name="ประเภทขยะ",
            ),
        ),
    ]
