# Generated by Django 5.1.4 on 2025-01-17 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("barcode_scanner", "0009_wasteimage_added_by_wasteitem_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wasteimage",
            name="correct_votes",
            field=models.ManyToManyField(
                blank=True,
                related_name="correct_waste_images",
                to=settings.AUTH_USER_MODEL,
                verbose_name="แยกถูก",
            ),
        ),
        migrations.AddField(
            model_name="wasteimage",
            name="incorrect_votes",
            field=models.ManyToManyField(
                blank=True,
                related_name="incorrect_waste_images",
                to=settings.AUTH_USER_MODEL,
                verbose_name="แยกผิด",
            ),
        ),
    ]
