# Generated by Django 5.1.4 on 2025-01-17 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("barcode_scanner", "0012_alter_wasteimage_waste_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wasteimage",
            name="waste_item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waste_images",
                to="barcode_scanner.wasteitem",
                verbose_name="รายการขยะ",
            ),
        ),
    ]
