# Generated by Django 5.1.4 on 2025-01-17 17:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("barcode_scanner", "0014_alter_wasteimage_waste_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wasteimage",
            name="waste_item",
        ),
    ]
