# Generated by Django 5.1.4 on 2025-01-17 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("barcode_scanner", "0015_remove_wasteimage_waste_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="wasteimage",
            name="waste_item",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="barcode_scanner.wasteitem",
                verbose_name="รายการขยะที่เชื่อมโยง",
            ),
            preserve_default=False,
        ),
    ]
