# Generated by Django 5.1.4 on 2025-01-17 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("barcode_scanner", "0016_wasteimage_waste_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wasteimage",
            name="waste_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="barcode_scanner.wasteitem",
                verbose_name="รายการขยะที่เชื่อมโยง",
            ),
        ),
    ]
