# Generated by Django 5.1.4 on 2025-02-21 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("barcode_scanner", "0017_alter_wasteimage_waste_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="wasteimage",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้เพิ่มข้อมูล",
            ),
        ),
        migrations.AlterField(
            model_name="wasteimage",
            name="waste_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="barcode_scanner.wasteitem",
                verbose_name="รายการขยะที่เชื่อมโยง",
            ),
        ),
        migrations.AlterField(
            model_name="wasteitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้สร้างผลิตภัณฑ์",
            ),
        ),
    ]
